#cs
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#ce

$n1=1
$n2=2
$t=0
While $n2 < 4000000
	If Mod($n2,2)=0 Then
		$t+=$n2
	EndIf
	$tmp=$n1+$n2
	$n1=$n2
	$n2=$tmp
WEnd
MsgBox(0,"",$t)
